version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/repo

jobs:
  build-and-test:
    executor: maven-executor
    steps:
      - checkout  # Step to check out code from your GitHub repo
      - run:
          name: Set up Maven Dependencies
          command: mvn dependency:resolve
      - run:
          name: Run API Tests
          command: mvn test
      - store_artifacts:
          path: target/surefire-reports
          destination: test-reports
      - store_test_results:
          path: target/surefire-reports/testng-results.xml

workflows:
  version: 2
  test-workflow:
    jobs:
      - build-and-test
